---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: sonarr
    run_list:
      - recipe[sonarr::default]
